server.port=8080
spring.application.name=zhenxiactivity
spring.profiles.active=dev
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false 
logging.level.org.springframework=debug
logging.level.com.example=DEBUG
spring.mvc.static-path-pattern=/static/**
spring.web.resources.static-locations=classpath:/static/